sudo: required
cache: bundler
services:
  - docker
env:
  global:
    - PATH=/opt/local/bin:$PATH
    - TESTOPTS="-v"
    - TINYTDS_UNIT_HOST=localhost
rvm:
  - 2.6.8
  - 2.7.4
  - 3.0.2
before_install:
  - docker info
  - docker-compose up -d
  - sudo ./test/bin/install-openssl.sh
  - sudo ./test/bin/install-freetds.sh
install:
  - gem install bundler
  - bundle --version
  - bundle install
script:
  - bundle exec rake
